build:
    environment:
        php:
            version: 7.1 
        mysql: 5.7
        variables:
            DB_TEST_USERNAME: root
            DB_USERNAME: root
    dependencies:
        before:
            - mysql -e 'create database cyber;'
            - mysql -e 'create database cyber_test;'
    tests:
        before:
            - touch .env
            - php artisan key:generate
checks:
    php:
        code_rating: true
        duplication: true
