build:
    environment:
        php:
            version: 7.1 
        mysql: 5.7
        variables:
            DB_TEST_USERNAME: root
            DB_USERNAME: root
            APP_KEY: base64:ApakOSikUFhPmEJK9wnsJideoBf0HMdP08JxrtB7JkE=
    dependencies:
        before:
            - mysql -e 'create database cyber;'
            - mysql -e 'create database cyber_test;'
checks:
    php:
        code_rating: true
        duplication: true
