language: php

php:
  - 7.3

env:
  - TRAVIS_NODE_VERSION="12"

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database cyber_test;'
  - yes '' | pecl install imagick
  - composer self-update
  - composer install --dev --no-interaction
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - yarn install
  - yarn build
  - php artisan key:generate
  - php artisan passport:keys
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm i -g phplint
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - phplint '**/*.php' '!vendor/**' '!storage/**'
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - yarn lint
  - php artisan code:analyse
  - fossa init
  - fossa analyze

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
  - cp build/logs/clover.xml coverage.xml
  - bash <(curl -s https://codecov.io/bash)

