language: php

php:
  - 7.1

env:
  - TRAVIS_NODE_VERSION="9"

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_script:
  - cp .env.travis .env
  - mysql -e 'create database cyber_test;'
  - composer self-update
  - composer install --dev --no-interaction
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - yarn install
  - yarn run production
  - php artisan key:generate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml

after_success:
  - php vendor/bin/codacycoverage clover build/coverage/xml
after_script:
  - ./cc-test-reporter after-build --exit-code
  - php vendor/bin/codacycoverage clover build/coverage/xml
