version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ROOT_PASSWORD=
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev libmagickwand-dev mariadb-client
      - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: yes '' | sudo pecl install imagick || true
      - run: sudo docker-php-ext-enable imagick
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: mysqladmin create cyber_test --user="root" --host="127.0.0.1"
      - run: php artisan key:generate
      - run: php artisan migrate --env=testing --database=testing --force --seed
      - run: php artisan passport:keys
      - run: php artisan config:cache
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
