name: REUSE

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  reuse-compliance:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Check REUSE compliance
        uses: fsfe/reuse-action@v6
